// export const domainsWithSkills = [
//     { domain: 'Web Development', skills: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'] },
//     { domain: 'Data Science', skills: ['Python', 'R', 'Machine Learning', 'TensorFlow', 'Pandas'] },
//     { domain: 'Mobile Development', skills: ['Java', 'Swift', 'Kotlin', 'React Native'] },
//     { domain: 'Cloud Computing', skills: ['AWS', 'Azure', 'Google Cloud', 'Docker', 'Kubernetes'] }
// ];

export const domainsWithSkills = {
    "Web Development": ["HTML", "CSS", "JavaScript", "React", "Node.js", "Vue.js", "Angular", "TypeScript", "Bootstrap", "Tailwind CSS"],
    "Data Science": ["Python", "R", "Pandas", "NumPy", "TensorFlow", "Scikit-Learn", "Matplotlib", "Seaborn", "Keras", "PyTorch"],
    "UI/UX Design": ["Figma", "Adobe XD", "Sketch", "InVision", "Wireframing", "Prototyping", "User Research"],
    "DevOps": ["Docker", "Kubernetes", "Jenkins", "AWS", "Terraform", "Git", "CI/CD", "Ansible", "Prometheus", "Grafana"],
    "Mobile Development": ["React Native", "Swift", "Kotlin", "Android", "iOS", "Flutter", "Firebase"],
    "Cloud Computing": ["AWS", "Azure", "Google Cloud", "Docker", "Kubernetes", "Serverless Computing", "Cloud Security", "Lambda"],
    "Artificial Intelligence": ["Machine Learning", "Deep Learning", "NLP", "Computer Vision", "Reinforcement Learning", "AI Ethics"],
    "Blockchain": ["Solidity", "Ethereum", "Hyperledger", "Truffle", "Ganache", "Smart Contracts", "Web3.js", "DeFi", "NFTs"],
    "Game Development": ["Unity", "Unreal Engine", "C#", "C++", "VR/AR", "Game Design", "3D Modeling", "Blender"],
    "Machine Learning": ["Machine Learning", "Deep Learning", "NLP", "Computer Vision", "Reinforcement Learning", "AutoML"],
    "Internet of Things": ["Arduino", "Raspberry Pi", "ESP8266", "ESP32", "IoT Security", "MQTT", "Embedded Systems"],
    "Cybersecurity": ["Penetration Testing", "Web Security", "Network Security", "Cybercrime", "Cryptography", "Ethical Hacking"],
    "Big Data": ["Hadoop", "Spark", "Kafka", "Hive", "Scala", "NoSQL", "Elasticsearch"],
    "Embedded Systems": ["C", "C++", "Microcontrollers", "RTOS", "FPGA", "PCB Design"],
    "Quantum Computing": ["Qiskit", "Quantum Algorithms", "Quantum Cryptography", "IBM Quantum Experience"],
    "Robotics": ["ROS", "Computer Vision", "Path Planning", "AI for Robotics", "Autonomous Systems"],
    "AR/VR Development": ["Unity", "Unreal Engine", "Oculus SDK", "HTC Vive", "3D Modeling", "Spatial Computing"],
    "Networking": ["CCNA", "Routing and Switching", "Network Security", "SDN", "Wireless Networks"],
    "Database Management": ["MySQL", "PostgreSQL", "MongoDB", "Redis", "Oracle", "SQL Server"],
    "Software Testing": ["Selenium", "JUnit", "TestNG", "Performance Testing", "Automation Testing"],
    "System Administration": ["Linux", "Windows Server", "Shell Scripting", "Active Directory"],
    "Ethical Hacking": ["Kali Linux", "Metasploit", "Burp Suite", "Wireshark"],
    "Augmented Reality": ["ARKit", "ARCore", "Vuforia", "OpenCV"],
    "3D Printing": ["CAD Design", "Fusion 360", "SolidWorks", "3D Slicing"],
    "E-commerce Development": ["Shopify", "WooCommerce", "Magento", "SEO"],
    "Financial Technology (FinTech)": ["Blockchain", "Smart Contracts", "DeFi", "Open Banking", "Financial Analysis"],
    "Content Management Systems (CMS)": ["WordPress", "Drupal", "Joomla", "Headless CMS"],
    "Natural Language Processing": ["NLTK", "SpaCy", "Transformers", "Chatbots", "Speech Recognition"],
    "Digital Marketing": ["SEO", "Google Ads", "Social Media Marketing", "Email Marketing", "Analytics"],
    "Computer Vision": ["OpenCV", "YOLO", "Deep Learning", "Object Detection"],
    "Bioinformatics": ["Biopython", "Genome Sequencing", "Molecular Biology", "R"],
};
